###################################################
#                   familyhelper                  #
###################################################
# \u5BFC\u51FA\u6A21\u677F\u6D41\u4E0B\u8F7D\u7684\u51ED\u8BC1\u7C7B\u578B\u3002
voucher_category_id.export_template_stream_download=your-category-id-here
# \u5BFC\u5165\u6A21\u677F\u6D41\u4E0B\u8F7D\u7684\u51ED\u8BC1\u7C7B\u578B\u3002
voucher_category_id.import_template_stream_download=your-category-id-here
# \u5BFC\u51FA\u6587\u4EF6\u6D41\u4E0B\u8F7D\u7684\u51ED\u8BC1\u7C7B\u578B\u3002
voucher_category_id.export_file_stream_download=your-category-id-here
# \u5BFC\u5165\u6587\u4EF6\u6D41\u4E0B\u8F7D\u7684\u51ED\u8BC1\u7C7B\u578B\u3002
voucher_category_id.import_file_stream_download=your-category-id-here